project:
  type: website

execute:
  echo: false

website:
  title: "Jonathan Kho"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: publications.qmd
        text: Publications
      - href: presentations.qmd
        text: Presentations
      - href: assets/Kho_CV.pdf
        text: CV

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



