---
title: "Jonathan Kho"
---

Hi there! I'm an Astronomy Ph.D. student at the University of Virginia studying supermassive black holes and galaxies in cosmological simulations. Take a look at what I've been up to lately!

## Research

### Supermassive Black Holes

So far as we can tell, at the center of every massive galaxy lies a supermassive black hole millions to tens of billions of times as massive as our Sun!
These black holes (BHs) can have a huge impact on their environment by launching relativistic jets that punch through their host galaxies and beyond (whereby they are called active galactic nuclei, or AGN), and are observed to have masses that correlate strongly with various properties of their hosts, like stellar mass and stellar velocity dispersion. 
While we have a well-developed understanding of how stellar-mass BHs can form from the death of a massive star, it is currently unknown how the first "seeds" of these cosmic monsters formed and grew to become supermassive. 
To make matters even more interesting, NASA's JWST has observed supermassive BHs to already exist in galaxies within the first billion years of the Universe!
These observations have proven extremely difficult for theorists to explain, as we are now asking how a BH can grow so big, so fast.

In order to help tackle this question, I've used the novel [BRAHMA](https://www.brahma-project.org/) seed models in cosmological simulations to probe the possibility that enhanced merger-driven BH growth can help explain JWST observations.
By implementing highly optimistic seeding models, the BHs in our simulations grew much faster at early times by merging with other BH seeds, enabling rapid BH growth in a regime where accretion-based growth is often less effective in simulations.
This resulted in a non-evolving $\rm M_\bullet-\sigma$ relation in the simulation using a leninet/optimistic seeding model, but an evolving relation in the simulations with more restrictive seeding models.
Tentative JWST relations indicate that the $\rm M_\bullet-\sigma$ relation may be constant over cosmic time, hinting that heavy BH seeds may form in greater abundances than previously thought possible.
To learn more, read my paper ["Signatures of Black Hole Seeding on the $\rm M_\bullet$-$\sigma$ Relation: Predictions from the BRAHMA Simulations"](https://ui.adsabs.harvard.edu/abs/2025ApJ...994..172K/abstract)!


My second paper studying supermassive BHs also used the BRAHMA seed models, but this time also included a novel BH accretion model.
When gas falls into a BH, the BH grows in mass and is said to have "accreted" the gas. 
We model this process using various subgrid models in cosmological simulations, as our resolution is too coarse to model it in detail. 
The most commonly adopted model, Bondi-Hoyle accretion, has a steep $\rm \dot{M}\propto M_\bullet^2$ scaling with the BH's mass, and thus lower-mass BH seeds have a greater difficulty growing quickly with this model.
To test whether a different accretion model could help produce supermassive BHs at early times, we used a model that has shallower $\rm \dot{M}\propto M_\bullet^{0.5 - 1}$ scalings with the BH mass, while also testing variations in the strength of AGN and stellar feedback in our simulations.
We found that while the new accretion model did produce stronger growth than the Bondi-Hoyle model, the difference was marginal in the presence of fiducial AGN and stellar feedback, and once these feedback regimes were reduced for heavy seeds, Bondi-Hoyle accretion always produced stronger BH growth.
Thus, the only way we were able to reproduce some JWST observations was via Bondi accretion with reduced feedback, or by producing many BH seeds at early times which rapidly merge with one another.
To learn more, read my paper ["Learning the Universe at High Redshifts: Impact of Accretion Modeling on Early Black Hole Growth"](https://arxiv.org/abs/2606.10036)!



### Uncertainty Quantification and DREAMs of FIRE



