---
title: "Publications"
---

# First-author Publications

## Learning the Universe at High Redshifts: Impact of Accretion Modeling on Early Black Hole Growth

{Kho}, Jonathan, {Bhowmick}, Aklant K., {Weinberger}, Rainer, {Torrey}, Paul, {Blecha}, Laura, {Hernquist}, Lars, {Bryan}, Greg L., {Garcia}, Alex M., {Ahvazi}, Niusha, {Saravia}, Alejandro, {Oh}, Boon Kiat

*arXiv e-prints*, 2026

[DOI](https://doi.org/10.48550/arXiv.2606.10036) | [ADS](https://ui.adsabs.harvard.edu/abs/2026arXiv260610036K) | [arXiv](https://arxiv.org/abs/2606.10036)

---

## Signatures of Black Hole Seeding on the M$_{\bullet}$─{\ensuremath{\sigma}} Relation: Predictions from the BRAHMA Simulations

{Kho}, Jonathan, {Bhowmick}, Aklant Kumar, {Torrey}, Paul, {Garcia}, Alex M., {Ahvazi}, Niusha, {Blecha}, Laura, {Vogelsberger}, Mark

*\apj*, 2025

[DOI](https://doi.org/10.3847/1538-4357/ae0e1e) | [ADS](https://ui.adsabs.harvard.edu/abs/2025ApJ...994..172K) | [arXiv](https://arxiv.org/abs/2506.17476)

---

## 3D Moving-Mesh Simulations of Type IIn Supernovae

{Kho}, Jonathan, {Mohamed}, Shazrene

*American Astronomical Society Meeting Abstracts \#243*, 2024

[ADS](https://ui.adsabs.harvard.edu/abs/2024AAS...24326014K)

---

# Co-authored Publications

## The DREAMS Project: Disentangling the Impact of Halo-to-halo Variance and Baryonic Feedback on Milky Way Dark Matter Density Profiles

{Garcia}, Alex M., {Rose}, Jonah C., {Torrey}, Paul, {Caputo}, Andrea, {Lisanti}, Mariangela, {Pace}, Andrew B., {Liu}, Hongwan, {Hussein}, Abdelaziz, {Liu}, Haozhe, {Villaescusa-Navarro}, Francisco, {Barry}, John, {Leisher}, Ilem, {Costanza}, Bel{\'e}n, {Kho}, Jonathan, {Lilie}, Ethan, {Li}, Jiaxuan, {Ahvazi}, Niusha, {Bhowmick}, Aklant, {Nguyen}, Tri, {O'Neil}, Stephanie, {Ou}, Xiaowei, {Shen}, Xuejian, {Farahi}, Arya, {Kallivayalil}, Nitya, {Necib}, Lina, {Vogelsberger}, Mark

*\apj*, 2026

[DOI](https://doi.org/10.3847/1538-4357/ae5938) | [ADS](https://ui.adsabs.harvard.edu/abs/2026ApJ..1002....8G) | [arXiv](https://arxiv.org/abs/2512.03132)

---

## Heavy Seeds and the First Black Holes: Insights from the BRAHMA Simulations

{Bhowmick}, Aklant K., {Blecha}, Laura, {Torrey}, Paul, {Kelley}, Luke Zoltan, {Natarajan}, Priyamvada, {Somerville}, Rachel S., {Weinberger}, Rainer, {Garcia}, Alex M., {Hernquist}, Lars, {Di Matteo}, Tiziana, {Kho}, Jonathan, {Vogelsberger}, Mark

*\apj*, 2026

[DOI](https://doi.org/10.3847/1538-4357/ae2607) | [ADS](https://ui.adsabs.harvard.edu/abs/2026ApJ...997..187B) | [arXiv](https://arxiv.org/abs/2510.01322)

---

## The abundance and properties of the lowest luminosity dwarf galaxies around the Milky Way: Insights from Semi-Analytic Models

{Ahvazi}, Niusha, {Pace}, Andrew B., {Garling}, Christopher T., {Ou}, Xiaowei, {Kallivayalil}, Nitya, {Torrey}, Paul, {Benson}, Andrew, {Bhowmick}, Aklant, {Torres-Alb{\`a}}, N{\'u}ria, {Garcia}, Alex M., {Saravia}, Alejandro, {Kho}, Jonathan, {Warfield}, Jack T., {Atzberger}, Kaia R.

*arXiv e-prints*, 2025

[DOI](https://doi.org/10.48550/arXiv.2511.15808) | [ADS](https://ui.adsabs.harvard.edu/abs/2025arXiv251115808A) | [arXiv](https://arxiv.org/abs/2511.15808)

---

## Signatures of black hole seeding in the local Universe: predictions from the BRAHMA cosmological simulations

{Bhowmick}, Aklant K., {Blecha}, Laura, {Torrey}, Paul, {Somerville}, Rachel S., {Kelley}, Luke Zoltan, {Weinberger}, Rainer, {Vogelsberger}, Mark, {Hernquist}, Lars, {Natarajan}, Priyamvada, {Kho}, Jonathan, {Di Matteo}, Tiziana

*\mnras*, 2025

[DOI](https://doi.org/10.1093/mnras/staf269) | [ADS](https://ui.adsabs.harvard.edu/abs/2025MNRAS.538..518B) | [arXiv](https://arxiv.org/abs/2411.19332)

---

